<a href="https://colab.research.google.com/github/Prarabdhaa/Data-Exploration/blob/master/Copy_of_weather_averaging_byweek.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import seaborn as sns
import matplotlib as plt

In [0]:
df = pd.read_excel("santa-maria2011-2019.xlsx")

In [0]:
df.count()

Date                    2922
ETo (in)                1987
Precip (in)             2921
Sol Rad (Ly/day)        2921
Avg Vap Pres (mBars)    2921
Max Air Temp (F)        2919
Min Air Temp (F)        2917
Avg Air Temp (F)        2918
Max Rel Hum (%)         2921
Min Rel Hum (%)         2921
Avg Rel Hum (%)         2893
Dew Point (F)           2893
Avg Wind Speed (mph)    2921
Avg Soil Temp (F)       2478
dtype: int64

In [0]:
df['Date'] = pd.to_datetime(df['Date'])
df_new = df.groupby([pd.Grouper(key='Date', freq='W-MON')]).mean()

In [0]:
df_new.count()

ETo (in)                285
Precip (in)             418
Sol Rad (Ly/day)        418
Avg Vap Pres (mBars)    418
Max Air Temp (F)        418
Min Air Temp (F)        418
Avg Air Temp (F)        418
Max Rel Hum (%)         418
Min Rel Hum (%)         418
Avg Rel Hum (%)         418
Dew Point (F)           418
Avg Wind Speed (mph)    418
Avg Soil Temp (F)       371
dtype: int64

In [0]:
df_new.reset_index()

          Date  ETo (in)  ...  Avg Wind Speed (mph)  Avg Soil Temp (F)
0   2011-04-04  0.112500  ...              3.825000          61.375000
1   2011-04-11  0.135714  ...              5.371429          58.442857
2   2011-04-18  0.168571  ...              7.557143          59.500000
3   2011-04-25  0.131429  ...              5.228571          62.828571
4   2011-05-02  0.215714  ...              6.900000          60.900000
5   2011-05-09  0.177143  ...              5.571429          62.414286
6   2011-05-16  0.157143  ...              5.257143          62.171429
7   2011-05-23  0.167143  ...              6.742857          62.657143
8   2011-05-30  0.200000  ...              7.728571          62.342857
9   2011-06-06  0.155714  ...              5.785714          62.571429
10  2011-06-13  0.152857  ...              6.014286          64.614286
11  2011-06-20  0.157143  ...              4.600000          66.314286
12  2011-06-27  0.172857  ...              5.071429          70.600000
13  2011-07-04  0.204286  ...              5.000000          69.314286
14  2011-07-11  0.178571  ...              4.857143          70.214286
15  2011-07-18  0.165714  ...              5.700000          69.457143
16  2011-07-25  0.158571  ...              4.671429          70.571429
17  2011-08-01  0.168571  ...              4.400000          70.071429
18  2011-08-08  0.162857  ...              4.914286          68.585714
19  2011-08-15  0.161429  ...              4.242857          68.757143
20  2011-08-22  0.150000  ...              4.857143          67.657143
21  2011-08-29  0.154286  ...              4.185714          68.128571
22  2011-09-05  0.134286  ...              4.014286          67.471429
23  2011-09-12  0.130000  ...              3.757143          67.400000
24  2011-09-19  0.135714  ...              3.785714          66.914286
25  2011-09-26  0.118571  ...              4.271429          67.100000
26  2011-10-03  0.127143  ...              3.728571          65.942857
27  2011-10-10  0.115714  ...              4.328571          63.214286
28  2011-10-17  0.141429  ...              4.642857          65.385714
29  2011-10-24  0.091429  ...              3.757143          65.900000
..         ...       ...  ...                   ...                ...
388 2018-09-10       NaN  ...              3.214286                NaN
389 2018-09-17       NaN  ...              3.557143                NaN
390 2018-09-24       NaN  ...              3.242857          71.700000
391 2018-10-01       NaN  ...              2.914286          72.020000
392 2018-10-08       NaN  ...              3.514286          70.785714
393 2018-10-15       NaN  ...              2.900000          69.700000
394 2018-10-22       NaN  ...              2.728571          68.014286
395 2018-10-29       NaN  ...              2.871429          67.671429
396 2018-11-05       NaN  ...              2.971429          67.600000
397 2018-11-12       NaN  ...              2.257143          64.228571
398 2018-11-19       NaN  ...              2.128571          63.457143
399 2018-11-26       NaN  ...              2.900000          63.142857
400 2018-12-03       NaN  ...              3.242857          60.814286
401 2018-12-10       NaN  ...              2.828571          58.457143
402 2018-12-17       NaN  ...              2.900000          57.757143
403 2018-12-24       NaN  ...              3.085714          58.542857
404 2018-12-31       NaN  ...              3.242857          54.642857
405 2019-01-07       NaN  ...              3.185714          52.885714
406 2019-01-14       NaN  ...              3.728571          56.514286
407 2019-01-21       NaN  ...              4.814286          57.085714
408 2019-01-28       NaN  ...              2.585714          55.942857
409 2019-02-04       NaN  ...              4.957143          57.442857
410 2019-02-11       NaN  ...              3.485714          53.328571
411 2019-02-18       NaN  ...              5.371429          53.600000
412 2019-02-25       NaN  ...              3.228571          51.928571
413 2019-03-04       NaN  ...              3.842857          56.800000
414 2019-03-11       NaN  ...              3.714286          56.485714
415 2019-03-18       NaN  ...              3.400000          56.742857
416 2019-03-25       NaN  ...              3.157143          58.557143
417 2019-04-01       NaN  ...              3.983333          60.816667

[418 rows x 14 columns]

In [0]:
df_new.to_excel('santa-maria2012-19.xlsx')

In [0]:
from google.colab import files
files.download('santa-maria2012-19.xlsx')