<a href="https://colab.research.google.com/github/Prarabdhaa/Data-Exploration/blob/master/Untitled9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
df = pd.read_excel('oxnard2005-16.xlsx')

In [147]:
df.head()

        Date  ETo (in)  ...  Avg Wind Speed (mph)  Avg Soil Temp (F)
0 2005-01-03  0.023333  ...              3.500000          52.700000
1 2005-01-10  0.024286  ...              5.328571          52.571429
2 2005-01-17  0.087143  ...              5.485714          53.314286
3 2005-01-24  0.085714  ...              3.514286          56.485714
4 2005-01-31  0.058571  ...              3.542857          56.328571

[5 rows x 14 columns]

In [148]:
df

          Date  ETo (in)  ...  Avg Wind Speed (mph)  Avg Soil Temp (F)
0   2005-01-03  0.023333  ...              3.500000          52.700000
1   2005-01-10  0.024286  ...              5.328571          52.571429
2   2005-01-17  0.087143  ...              5.485714          53.314286
3   2005-01-24  0.085714  ...              3.514286          56.485714
4   2005-01-31  0.058571  ...              3.542857          56.328571
5   2005-02-07  0.101429  ...              4.100000          54.914286
6   2005-02-14  0.074286  ...              3.728571          56.985714
7   2005-02-21  0.045714  ...              4.614286          58.571429
8   2005-02-28  0.078571  ...              3.671429          58.957143
9   2005-03-07  0.088571  ...              3.571429          60.600000
10  2005-03-14  0.088571  ...              3.757143          63.728571
11  2005-03-21  0.101429  ...              4.700000          61.000000
12  2005-03-28  0.117143  ...              5.557143          59.557143
13  2005-04-04  0.171429  ...              5.271429          61.214286
14  2005-04-11  0.164286  ...              6.242857          61.714286
15  2005-04-18  0.158571  ...              3.914286          63.400000
16  2005-04-25  0.155714  ...              4.557143          64.357143
17  2005-05-02  0.160000  ...              4.285714          66.242857
18  2005-05-09  0.147143  ...              4.871429          67.228571
19  2005-05-16  0.192857  ...              4.228571          68.214286
20  2005-05-23  0.185714  ...              3.671429          71.771429
21  2005-05-30  0.111429  ...              4.271429          71.942857
22  2005-06-06  0.131429  ...              4.385714          72.542857
23  2005-06-13  0.162857  ...              3.257143          73.400000
24  2005-06-20  0.140000  ...              1.000000          73.185714
25  2005-06-27  0.182857  ...              1.628571          73.928571
26  2005-07-04  0.142857  ...              4.257143          74.285714
27  2005-07-11  0.162857  ...              3.857143          75.371429
28  2005-07-18  0.150000  ...              4.571429          77.100000
29  2005-07-25  0.191429  ...              4.428571          80.114286
..         ...       ...  ...                   ...                ...
587 2016-04-04  0.158571  ...              5.000000          63.757143
588 2016-04-11  0.105714  ...              3.971429          65.214286
589 2016-04-18  0.198571  ...              5.200000          66.214286
590 2016-04-25  0.204286  ...              6.042857          67.814286
591 2016-05-02  0.174286  ...              5.542857          67.714286
592 2016-05-09  0.150000  ...              4.457143          69.028571
593 2016-05-16  0.122857  ...              4.171429          70.014286
594 2016-05-23  0.151429  ...              5.014286          69.914286
595 2016-05-30  0.158571  ...              4.971429          70.500000
596 2016-06-06  0.105714  ...              4.328571          71.028571
597 2016-06-13  0.114286  ...              4.328571          71.285714
598 2016-06-20  0.190000  ...              4.671429          71.657143
599 2016-06-27  0.150000  ...              4.100000          73.842857
600 2016-07-04  0.172857  ...              4.828571          75.614286
601 2016-07-11  0.172857  ...              4.757143          75.685714
602 2016-07-18  0.185714  ...              4.814286          76.328571
603 2016-07-25  0.210000  ...              4.528571          76.857143
604 2016-08-01  0.178571  ...              4.528571          78.328571
605 2016-08-08  0.168571  ...              4.671429          78.028571
606 2016-08-15  0.172857  ...              4.971429          77.571429
607 2016-08-22  0.162857  ...              4.800000          77.500000
608 2016-08-29  0.150000  ...              4.257143          76.500000
609 2016-09-05  0.158571  ...              4.457143          76.028571
610 2016-09-12  0.108571  ...              4.671429          75.214286
611 2016-09-19  0.138571  ...              4.057143          74.371429
612 2016-09-26  0.168571  ...              4.771429          74.500000
613 2016-10-03  0.151429  ...              4.071429          74.685714
614 2016-10-10  0.147143  ...              4.300000          72.700000
615 2016-10-17  0.095714  ...              4.557143          71.728571
616 2016-10-24  0.177500  ...              4.850000          71.100000

[617 rows x 14 columns]

In [0]:
df_new = df.iloc[61:]

In [150]:
df_new

          Date  ETo (in)  ...  Avg Wind Speed (mph)  Avg Soil Temp (F)
61  2006-03-06  0.090000  ...              4.485714          56.928571
62  2006-03-13  0.100000  ...              5.842857          55.014286
63  2006-03-20  0.107143  ...              4.971429          55.071429
64  2006-03-27  0.118571  ...              4.371429          57.100000
65  2006-04-03  0.084286  ...              3.528571          58.971429
66  2006-04-10  0.114286  ...              5.014286          60.071429
67  2006-04-17  0.128571  ...              4.928571          62.314286
68  2006-04-24  0.144286  ...              4.457143          63.242857
69  2006-05-01  0.081429  ...              4.028571          64.728571
70  2006-05-08  0.100000  ...              4.128571          65.385714
71  2006-05-15  0.084286  ...              3.785714          67.071429
72  2006-05-22  0.094286  ...              3.928571          69.171429
73  2006-05-29  0.202857  ...              4.457143          70.357143
74  2006-06-05  0.181429  ...              4.014286          72.400000
75  2006-06-12  0.115714  ...              4.971429          73.057143
76  2006-06-19  0.188571  ...              4.371429          77.100000
77  2006-06-26  0.138571  ...              4.700000          77.900000
78  2006-07-03  0.187143  ...              4.457143          78.514286
79  2006-07-10  0.200000  ...              4.757143          79.128571
80  2006-07-17  0.192857  ...              4.485714          79.657143
81  2006-07-24  0.177143  ...              4.528571          82.200000
82  2006-07-31  0.140000  ...              4.528571          83.128571
83  2006-08-07  0.165714  ...              4.700000          80.785714
84  2006-08-14  0.177143  ...              4.642857          80.342857
85  2006-08-21  0.170000  ...              4.571429          79.614286
86  2006-08-28  0.167143  ...              4.500000          78.871429
87  2006-09-04  0.170000  ...              4.414286          78.685714
88  2006-09-11  0.142857  ...              4.314286          77.371429
89  2006-09-18  0.128571  ...              4.014286          76.271429
90  2006-09-25  0.140000  ...              4.242857          74.585714
..         ...       ...  ...                   ...                ...
587 2016-04-04  0.158571  ...              5.000000          63.757143
588 2016-04-11  0.105714  ...              3.971429          65.214286
589 2016-04-18  0.198571  ...              5.200000          66.214286
590 2016-04-25  0.204286  ...              6.042857          67.814286
591 2016-05-02  0.174286  ...              5.542857          67.714286
592 2016-05-09  0.150000  ...              4.457143          69.028571
593 2016-05-16  0.122857  ...              4.171429          70.014286
594 2016-05-23  0.151429  ...              5.014286          69.914286
595 2016-05-30  0.158571  ...              4.971429          70.500000
596 2016-06-06  0.105714  ...              4.328571          71.028571
597 2016-06-13  0.114286  ...              4.328571          71.285714
598 2016-06-20  0.190000  ...              4.671429          71.657143
599 2016-06-27  0.150000  ...              4.100000          73.842857
600 2016-07-04  0.172857  ...              4.828571          75.614286
601 2016-07-11  0.172857  ...              4.757143          75.685714
602 2016-07-18  0.185714  ...              4.814286          76.328571
603 2016-07-25  0.210000  ...              4.528571          76.857143
604 2016-08-01  0.178571  ...              4.528571          78.328571
605 2016-08-08  0.168571  ...              4.671429          78.028571
606 2016-08-15  0.172857  ...              4.971429          77.571429
607 2016-08-22  0.162857  ...              4.800000          77.500000
608 2016-08-29  0.150000  ...              4.257143          76.500000
609 2016-09-05  0.158571  ...              4.457143          76.028571
610 2016-09-12  0.108571  ...              4.671429          75.214286
611 2016-09-19  0.138571  ...              4.057143          74.371429
612 2016-09-26  0.168571  ...              4.771429          74.500000
613 2016-10-03  0.151429  ...              4.071429          74.685714
614 2016-10-10  0.147143  ...              4.300000          72.700000
615 2016-10-17  0.095714  ...              4.557143          71.728571
616 2016-10-24  0.177500  ...              4.850000          71.100000

[556 rows x 14 columns]

In [0]:
a = np.array(df_new.iloc[60])

In [151]:
df_new['Date'] = pd.to_datetime(df_new['Date'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [152]:
df_new['DATE'] = df_new['Date'].dt.date

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [0]:
df_new = df_new.drop('Date', axis=1)

In [71]:
df_new

     ETo (in)  Precip (in)  ...  Avg Soil Temp (F)        DATE
61   0.090000     0.182857  ...          56.928571  2006-03-06
62   0.100000     0.055714  ...          55.014286  2006-03-13
63   0.107143     0.054286  ...          55.071429  2006-03-20
64   0.118571     0.028571  ...          57.100000  2006-03-27
65   0.084286     0.398571  ...          58.971429  2006-04-03
66   0.114286     0.292857  ...          60.071429  2006-04-10
67   0.128571     0.047143  ...          62.314286  2006-04-17
68   0.144286     0.000000  ...          63.242857  2006-04-24
69   0.081429     0.000000  ...          64.728571  2006-05-01
70   0.100000     0.001429  ...          65.385714  2006-05-08
71   0.084286     0.004286  ...          67.071429  2006-05-15
72   0.094286     0.135714  ...          69.171429  2006-05-22
73   0.202857     0.000000  ...          70.357143  2006-05-29
74   0.181429     0.000000  ...          72.400000  2006-06-05
75   0.115714     0.001429  ...          73.057143  2006-06-12
76   0.188571     0.000000  ...          77.100000  2006-06-19
77   0.138571     0.000000  ...          77.900000  2006-06-26
78   0.187143     0.000000  ...          78.514286  2006-07-03
79   0.200000     0.000000  ...          79.128571  2006-07-10
80   0.192857     0.000000  ...          79.657143  2006-07-17
81   0.177143     0.000000  ...          82.200000  2006-07-24
82   0.140000     0.000000  ...          83.128571  2006-07-31
83   0.165714     0.002857  ...          80.785714  2006-08-07
84   0.177143     0.000000  ...          80.342857  2006-08-14
85   0.170000     0.000000  ...          79.614286  2006-08-21
86   0.167143     0.000000  ...          78.871429  2006-08-28
87   0.170000     0.000000  ...          78.685714  2006-09-04
88   0.142857     0.000000  ...          77.371429  2006-09-11
89   0.128571     0.000000  ...          76.271429  2006-09-18
90   0.140000     0.000000  ...          74.585714  2006-09-25
..        ...          ...  ...                ...         ...
587  0.158571     0.000000  ...          63.757143  2016-04-04
588  0.105714     0.025714  ...          65.214286  2016-04-11
589  0.198571     0.000000  ...          66.214286  2016-04-18
590  0.204286     0.001429  ...          67.814286  2016-04-25
591  0.174286     0.002857  ...          67.714286  2016-05-02
592  0.150000     0.000000  ...          69.028571  2016-05-09
593  0.122857     0.002857  ...          70.014286  2016-05-16
594  0.151429     0.004286  ...          69.914286  2016-05-23
595  0.158571     0.000000  ...          70.500000  2016-05-30
596  0.105714     0.000000  ...          71.028571  2016-06-06
597  0.114286     0.000000  ...          71.285714  2016-06-13
598  0.190000     0.000000  ...          71.657143  2016-06-20
599  0.150000     0.000000  ...          73.842857  2016-06-27
600  0.172857     0.000000  ...          75.614286  2016-07-04
601  0.172857     0.000000  ...          75.685714  2016-07-11
602  0.185714     0.000000  ...          76.328571  2016-07-18
603  0.210000     0.000000  ...          76.857143  2016-07-25
604  0.178571     0.000000  ...          78.328571  2016-08-01
605  0.168571     0.000000  ...          78.028571  2016-08-08
606  0.172857     0.000000  ...          77.571429  2016-08-15
607  0.162857     0.000000  ...          77.500000  2016-08-22
608  0.150000     0.000000  ...          76.500000  2016-08-29
609  0.158571     0.000000  ...          76.028571  2016-09-05
610  0.108571     0.000000  ...          75.214286  2016-09-12
611  0.138571     0.000000  ...          74.371429  2016-09-19
612  0.168571     0.000000  ...          74.500000  2016-09-26
613  0.151429     0.000000  ...          74.685714  2016-10-03
614  0.147143     0.000000  ...          72.700000  2016-10-10
615  0.095714     0.007143  ...          71.728571  2016-10-17
616  0.177500     0.000000  ...          71.100000  2016-10-24

[556 rows x 14 columns]

In [0]:
df = df_new

In [154]:
df

          Date  ETo (in)  ...  Avg Soil Temp (F)        DATE
61  2006-03-06  0.090000  ...          56.928571  2006-03-06
62  2006-03-13  0.100000  ...          55.014286  2006-03-13
63  2006-03-20  0.107143  ...          55.071429  2006-03-20
64  2006-03-27  0.118571  ...          57.100000  2006-03-27
65  2006-04-03  0.084286  ...          58.971429  2006-04-03
66  2006-04-10  0.114286  ...          60.071429  2006-04-10
67  2006-04-17  0.128571  ...          62.314286  2006-04-17
68  2006-04-24  0.144286  ...          63.242857  2006-04-24
69  2006-05-01  0.081429  ...          64.728571  2006-05-01
70  2006-05-08  0.100000  ...          65.385714  2006-05-08
71  2006-05-15  0.084286  ...          67.071429  2006-05-15
72  2006-05-22  0.094286  ...          69.171429  2006-05-22
73  2006-05-29  0.202857  ...          70.357143  2006-05-29
74  2006-06-05  0.181429  ...          72.400000  2006-06-05
75  2006-06-12  0.115714  ...          73.057143  2006-06-12
76  2006-06-19  0.188571  ...          77.100000  2006-06-19
77  2006-06-26  0.138571  ...          77.900000  2006-06-26
78  2006-07-03  0.187143  ...          78.514286  2006-07-03
79  2006-07-10  0.200000  ...          79.128571  2006-07-10
80  2006-07-17  0.192857  ...          79.657143  2006-07-17
81  2006-07-24  0.177143  ...          82.200000  2006-07-24
82  2006-07-31  0.140000  ...          83.128571  2006-07-31
83  2006-08-07  0.165714  ...          80.785714  2006-08-07
84  2006-08-14  0.177143  ...          80.342857  2006-08-14
85  2006-08-21  0.170000  ...          79.614286  2006-08-21
86  2006-08-28  0.167143  ...          78.871429  2006-08-28
87  2006-09-04  0.170000  ...          78.685714  2006-09-04
88  2006-09-11  0.142857  ...          77.371429  2006-09-11
89  2006-09-18  0.128571  ...          76.271429  2006-09-18
90  2006-09-25  0.140000  ...          74.585714  2006-09-25
..         ...       ...  ...                ...         ...
587 2016-04-04  0.158571  ...          63.757143  2016-04-04
588 2016-04-11  0.105714  ...          65.214286  2016-04-11
589 2016-04-18  0.198571  ...          66.214286  2016-04-18
590 2016-04-25  0.204286  ...          67.814286  2016-04-25
591 2016-05-02  0.174286  ...          67.714286  2016-05-02
592 2016-05-09  0.150000  ...          69.028571  2016-05-09
593 2016-05-16  0.122857  ...          70.014286  2016-05-16
594 2016-05-23  0.151429  ...          69.914286  2016-05-23
595 2016-05-30  0.158571  ...          70.500000  2016-05-30
596 2016-06-06  0.105714  ...          71.028571  2016-06-06
597 2016-06-13  0.114286  ...          71.285714  2016-06-13
598 2016-06-20  0.190000  ...          71.657143  2016-06-20
599 2016-06-27  0.150000  ...          73.842857  2016-06-27
600 2016-07-04  0.172857  ...          75.614286  2016-07-04
601 2016-07-11  0.172857  ...          75.685714  2016-07-11
602 2016-07-18  0.185714  ...          76.328571  2016-07-18
603 2016-07-25  0.210000  ...          76.857143  2016-07-25
604 2016-08-01  0.178571  ...          78.328571  2016-08-01
605 2016-08-08  0.168571  ...          78.028571  2016-08-08
606 2016-08-15  0.172857  ...          77.571429  2016-08-15
607 2016-08-22  0.162857  ...          77.500000  2016-08-22
608 2016-08-29  0.150000  ...          76.500000  2016-08-29
609 2016-09-05  0.158571  ...          76.028571  2016-09-05
610 2016-09-12  0.108571  ...          75.214286  2016-09-12
611 2016-09-19  0.138571  ...          74.371429  2016-09-19
612 2016-09-26  0.168571  ...          74.500000  2016-09-26
613 2016-10-03  0.151429  ...          74.685714  2016-10-03
614 2016-10-10  0.147143  ...          72.700000  2016-10-10
615 2016-10-17  0.095714  ...          71.728571  2016-10-17
616 2016-10-24  0.177500  ...          71.100000  2016-10-24

[556 rows x 15 columns]

In [0]:
cols = list(df.columns.values)

In [156]:
cols

['Date',
 'ETo (in)',
 'Precip (in)',
 'Sol Rad (Ly/day)',
 'Avg Vap Pres (mBars)',
 'Max Air Temp (F)',
 'Min Air Temp (F)',
 'Avg Air Temp (F)',
 'Max Rel Hum (%)',
 'Min Rel Hum (%)',
 'Avg Rel Hum (%)',
 'Dew Point (F)',
 'Avg Wind Speed (mph)',
 'Avg Soil Temp (F)',
 'DATE']

In [0]:
df = df[['DATE',
 'ETo (in)',
 'Precip (in)',
 'Sol Rad (Ly/day)',
 'Avg Vap Pres (mBars)',
 'Max Air Temp (F)',
 'Min Air Temp (F)',
 'Avg Air Temp (F)',
 'Max Rel Hum (%)',
 'Min Rel Hum (%)',
 'Avg Rel Hum (%)',
 'Dew Point (F)',
 'Avg Wind Speed (mph)',
 'Avg Soil Temp (F)']]

In [158]:
df

           DATE  ETo (in)  ...  Avg Wind Speed (mph)  Avg Soil Temp (F)
61   2006-03-06  0.090000  ...              4.485714          56.928571
62   2006-03-13  0.100000  ...              5.842857          55.014286
63   2006-03-20  0.107143  ...              4.971429          55.071429
64   2006-03-27  0.118571  ...              4.371429          57.100000
65   2006-04-03  0.084286  ...              3.528571          58.971429
66   2006-04-10  0.114286  ...              5.014286          60.071429
67   2006-04-17  0.128571  ...              4.928571          62.314286
68   2006-04-24  0.144286  ...              4.457143          63.242857
69   2006-05-01  0.081429  ...              4.028571          64.728571
70   2006-05-08  0.100000  ...              4.128571          65.385714
71   2006-05-15  0.084286  ...              3.785714          67.071429
72   2006-05-22  0.094286  ...              3.928571          69.171429
73   2006-05-29  0.202857  ...              4.457143          70.357143
74   2006-06-05  0.181429  ...              4.014286          72.400000
75   2006-06-12  0.115714  ...              4.971429          73.057143
76   2006-06-19  0.188571  ...              4.371429          77.100000
77   2006-06-26  0.138571  ...              4.700000          77.900000
78   2006-07-03  0.187143  ...              4.457143          78.514286
79   2006-07-10  0.200000  ...              4.757143          79.128571
80   2006-07-17  0.192857  ...              4.485714          79.657143
81   2006-07-24  0.177143  ...              4.528571          82.200000
82   2006-07-31  0.140000  ...              4.528571          83.128571
83   2006-08-07  0.165714  ...              4.700000          80.785714
84   2006-08-14  0.177143  ...              4.642857          80.342857
85   2006-08-21  0.170000  ...              4.571429          79.614286
86   2006-08-28  0.167143  ...              4.500000          78.871429
87   2006-09-04  0.170000  ...              4.414286          78.685714
88   2006-09-11  0.142857  ...              4.314286          77.371429
89   2006-09-18  0.128571  ...              4.014286          76.271429
90   2006-09-25  0.140000  ...              4.242857          74.585714
..          ...       ...  ...                   ...                ...
587  2016-04-04  0.158571  ...              5.000000          63.757143
588  2016-04-11  0.105714  ...              3.971429          65.214286
589  2016-04-18  0.198571  ...              5.200000          66.214286
590  2016-04-25  0.204286  ...              6.042857          67.814286
591  2016-05-02  0.174286  ...              5.542857          67.714286
592  2016-05-09  0.150000  ...              4.457143          69.028571
593  2016-05-16  0.122857  ...              4.171429          70.014286
594  2016-05-23  0.151429  ...              5.014286          69.914286
595  2016-05-30  0.158571  ...              4.971429          70.500000
596  2016-06-06  0.105714  ...              4.328571          71.028571
597  2016-06-13  0.114286  ...              4.328571          71.285714
598  2016-06-20  0.190000  ...              4.671429          71.657143
599  2016-06-27  0.150000  ...              4.100000          73.842857
600  2016-07-04  0.172857  ...              4.828571          75.614286
601  2016-07-11  0.172857  ...              4.757143          75.685714
602  2016-07-18  0.185714  ...              4.814286          76.328571
603  2016-07-25  0.210000  ...              4.528571          76.857143
604  2016-08-01  0.178571  ...              4.528571          78.328571
605  2016-08-08  0.168571  ...              4.671429          78.028571
606  2016-08-15  0.172857  ...              4.971429          77.571429
607  2016-08-22  0.162857  ...              4.800000          77.500000
608  2016-08-29  0.150000  ...              4.257143          76.500000
609  2016-09-05  0.158571  ...              4.457143          76.028571
610  2016-09-12  0.108571  ...              4.671429          75.214286
611  2016-09-19  0.138571  ...              4.057143          74.371429
612  2016-09-26  0.168571  ...              4.771429          74.500000
613  2016-10-03  0.151429  ...              4.071429          74.685714
614  2016-10-10  0.147143  ...              4.300000          72.700000
615  2016-10-17  0.095714  ...              4.557143          71.728571
616  2016-10-24  0.177500  ...              4.850000          71.100000

[556 rows x 14 columns]

In [239]:
a = np.array([df.iloc[0]])
a.shape

(1, 14)

In [0]:
df

In [241]:
a = np.append(a, [df.iloc[1]])
a = np.append(a, [df.iloc[120]])
#b = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
#b.shape
#b = np.concatenate((a,b))
#b.shape
#b
a = np.reshape(a, (1, -1))
a.shape
a

array([[datetime.date(2006, 3, 6), 0.09, 0.1828571428571429,
        367.1428571428572, 11.12857142857143, 59.31428571428572,
        44.51428571428572, 52.4, 94.85714285714286, 63.71428571428572,
        82.57142857142857, 47.18571428571429, 4.485714285714286,
        56.92857142857143, datetime.date(2006, 3, 13),
        0.09999999999999999, 0.05571428571428572, 389.2857142857143,
        9.285714285714286, 56.1, 41.7, 49.14285714285715,
        92.57142857142857, 61.57142857142857, 77.57142857142857,
        42.35714285714285, 5.842857142857143, 55.01428571428571,
        datetime.date(2008, 6, 23), 0.23, 0.0, 705.1428571428571,
        16.24285714285714, 77.42857142857143, 57.32857142857143,
        67.04285714285714, 90.14285714285714, 54.85714285714285,
        72.14285714285714, 57.61428571428571, 3.857142857142857,
        74.18571428571428, datetime.date(2006, 3, 13),
        0.09999999999999999, 0.05571428571428572, 389.2857142857143,
        9.285714285714286, 56.1, 41.7, 49.14285714285715,
        92.57142857142857, 61.57142857142857, 77.57142857142857,
        42.35714285714285, 5.842857142857143, 55.01428571428571,
        datetime.date(2008, 6, 23), 0.23, 0.0, 705.1428571428571,
        16.24285714285714, 77.42857142857143, 57.32857142857143,
        67.04285714285714, 90.14285714285714, 54.85714285714285,
        72.14285714285714, 57.61428571428571, 3.857142857142857,
        74.18571428571428]], dtype=object)

In [199]:
c = np.concatenate((a,b), axis=0)

ValueError: ignored

In [0]:
i=0
i = str(i)
b = 'b'+i

In [105]:
for i in range(537):
  j = str(i)
  'a'+j = np.array(0)

SyntaxError: ignored

In [0]:
b = np.array([[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
#print(b)
for i in range(537):
  arr = np.array([[0,0,0,0,0,0,0,0,0,0,0,0,0,0]])
  #print(arr)
  for j in range(20):
    k = i+j
    arr = np.append(arr, df.iloc[k])
    #print(arr)
  #print(arr.shape)
  arr = np.reshape(arr, (1,-1))
  #print(arr.shape)
  #print(b.shape)
  b = np.concatenate((b,arr), axis=0)
  #print(b)

In [271]:
b.shape

(538, 294)

In [0]:
features = pd.DataFrame(b)

In [273]:
features

    0   1   2   3   4    ...      289      290      291      292      293
0     0   0   0   0   0  ...        0        0        0        0        0
1     0   0   0   0   0  ...  72.8571  87.5714  62.0571  4.48571  79.6571
2     0   0   0   0   0  ...  75.4286       88  66.6571  4.52857     82.2
3     0   0   0   0   0  ...  81.7143     90.2    67.86  4.52857  83.1286
4     0   0   0   0   0  ...  73.2857  84.2857  62.4286      4.7  80.7857
5     0   0   0   0   0  ...  74.7143  86.4286  62.2571  4.64286  80.3429
6     0   0   0   0   0  ...  74.7143  86.2857  60.6143  4.57143  79.6143
7     0   0   0   0   0  ...  76.7143  89.7143     60.5      4.5  78.8714
8     0   0   0   0   0  ...       52  79.7143  55.9571  4.41429  78.6857
9     0   0   0   0   0  ...  76.5714  87.5714  59.1857  4.31429  77.3714
10    0   0   0   0   0  ...  60.1429  77.4286  56.2286  4.01429  76.2714
11    0   0   0   0   0  ...  69.1429  83.7143  58.0714  4.24286  74.5857
12    0   0   0   0   0  ...  76.8571  87.8571     58.8  3.88571  73.0714
13    0   0   0   0   0  ...  69.5714  83.7143  55.4286  4.15714  71.4143
14    0   0   0   0   0  ...  68.1429       82     55.4  3.67143  70.8714
15    0   0   0   0   0  ...       37  65.7143  49.9714  4.08571  69.3286
16    0   0   0   0   0  ...       35       59  44.7286  3.82857  68.1143
17    0   0   0   0   0  ...  55.1429  72.7143     52.7  3.87143  67.2429
18    0   0   0   0   0  ...  37.8571  64.7143     48.5  3.68571  66.2714
19    0   0   0   0   0  ...  47.5714  75.1429  53.1143  3.44286     65.3
20    0   0   0   0   0  ...  54.2857  76.2857       49  3.74286  63.7286
21    0   0   0   0   0  ...  14.2857  30.1429  23.7286  4.98571  59.1857
22    0   0   0   0   0  ...  41.2857  71.1429  46.0714  4.08571     58.8
23    0   0   0   0   0  ...  51.2857  74.4286  45.5714      3.7  56.9286
24    0   0   0   0   0  ...  28.4286  54.8571  36.2429  3.95714  51.8857
25    0   0   0   0   0  ...  40.4286  64.5714  40.1714  4.42857  51.3429
26    0   0   0   0   0  ...  25.2857  45.4286  33.5571  4.71429  51.1571
27    0   0   0   0   0  ...  23.7143  40.5714  25.0143  4.35714     51.2
28    0   0   0   0   0  ...  22.1429  51.8571  30.8714  4.21429  48.2571
29    0   0   0   0   0  ...  49.8571       76  44.2143  2.88571  51.0571
..   ..  ..  ..  ..  ..  ...      ...      ...      ...      ...      ...
508   0   0   0   0   0  ...  58.8571  80.8571  50.4286        5  63.7571
509   0   0   0   0   0  ...  66.8571     89.5  57.6833  3.97143  65.2143
510   0   0   0   0   0  ...  39.7143  68.1667  49.7333      5.2  66.2143
511   0   0   0   0   0  ...  39.4286  64.8571  49.1857  6.04286  67.8143
512   0   0   0   0   0  ...  59.5714  79.5714  50.8857  5.54286  67.7143
513   0   0   0   0   0  ...  62.7143  87.2857  56.3714  4.45714  69.0286
514   0   0   0   0   0  ...  71.5714  94.5714  58.8286  4.17143  70.0143
515   0   0   0   0   0  ...  64.5714  86.1429  55.3571  5.01429  69.9143
516   0   0   0   0   0  ...       67       88     56.9  4.97143     70.5
517   0   0   0   0   0  ...  84.5714      100  63.4286  4.32857  71.0286
518   0   0   0   0   0  ...  84.7143  96.4286  61.0286  4.32857  71.2857
519   0   0   0   0   0  ...       59  85.8571  58.6571  4.67143  71.6571
520   0   0   0   0   0  ...  79.7143      100    64.75      4.1  73.8429
521   0   0   0   0   0  ...  71.7143     88.8     62.3  4.82857  75.6143
522   0   0   0   0   0  ...  69.5714  98.4286  64.8857  4.75714  75.6857
523   0   0   0   0   0  ...  69.2857  99.8571  66.2286  4.81429  76.3286
524   0   0   0   0   0  ...  63.2857     93.8     66.2  4.52857  76.8571
525   0   0   0   0   0  ...  70.7143      100    68.05  4.52857  78.3286
526   0   0   0   0   0  ...  71.7143      100     65.6  4.67143  78.0286
527   0   0   0   0   0  ...  71.2857      NaN      NaN  4.97143  77.5714
528   0   0   0   0   0  ...  70.4286      NaN      NaN      4.8     77.5
529   0   0   0   0   0  ...  68.4286      100    65.35  4.25714     76.5
530   0   0   0   0   0  ...  66.7143       98    63.95  4.45714  76.0286
531   0   0   0   0   0  ...  73.5714  89.7143  61.7714  4.67143  75.2143
532   0   0   0   0   0  ...  65.5714       82  57.7857  4.05714  74.3714
533   0   0   0   0   0  ...  32.8571     60.4    54.18  4.77143     74.5
534   0   0   0   0   0  ...  51.5714     74.5  57.8833  4.07143  74.6857
535   0   0   0   0   0  ...     37.5       61  50.5667      4.3     72.7
536   0   0   0   0   0  ...  70.4286  86.7143  57.7571  4.55714  71.7286
537   0   0   0   0   0  ...    19.25    40.25   43.625     4.85     71.1

[538 rows x 294 columns]